### ISSUE TITLE
"final' is not mentioned in the list of keywords

### ISSUE THREAD

**Issue by SmaugTheTerrible** [alx71hub/hcb#3]
keyword `final` used in `class-virt-specifier` and `virt-specifier` but not mentioned in keywords list
https://en.cppreference.com/w/cpp/keyword/final

**Comment by alx71hub** [comment]
The following identifiers are not keywords in that they are identifiers with special meaning, which may be used as names of objects or functions, but have special meaning in certain contexts:
- override
- final
- transaction_safe 
- transaction_safe_dynamic 
- import
- module
