### ISSUE TITLE
"override" is not mentioned in the list of keywords

### ISSUE THREAD

**Issue by npuschke** [alx71hub/hcb#4]
keyword `override` used in `virt-specifier` but not mentioned in keywords list
https://en.cppreference.com/w/cpp/keyword/override

**Comment by alx71hub** [comment]
From the link you added:
```
override is an identifier with a special meaning when used after member function declarators: it's not a reserved keyword otherwise
```

To be more specific, the following identifiers are not keywords in that they are identifiers with special meaning, which may be used as names of objects or functions, but have special meaning in certain contexts:
- override
- final
- transaction_safe 
- transaction_safe_dynamic 
- import
- module
