### ISSUE TITLE
Missing `-or-` in `for-range-initializer`

### ISSUE THREAD

**Issue by kmyk** [alx71hub/hcb#5]
The current version says `for-range-initializer` is a concatenation of `expression` and `braced-init-list`.

```
for-range-initializer:
    expression braced-init-list     C++0x
```

However, it seems the disjunction is correct instead of concatenation.

- https://www.nongnu.org/hcb/#for-range-initializer
- https://eel.is/c++draft/stmt.iter#nt:for-range-initializer

**Comment by alx71hub** [comment]
Fixed
